name: chip80
version: 0.1.0
category: game
license: GPL-3

extra-source-files:
  - README.md
  - import/ZX0/src/*.h
  - import/ZX0/src/*.c

dependencies:
  - base
  - z80
  - bytestring
  - filepath
  - directory
  - yaml
  - aeson
  - text
  - JuicyPixels

source-dirs:
  - src

c-sources:
  - import/ZX0/src/compress.c
  - import/ZX0/src/optimize.c
  - import/ZX0/src/memory.c

executables:
  chip80-homelab2:
    main: main.hs
