name: chip80
version: 0.1.0
category: game
license: GPL-3

extra-source-files:
  - README.md

dependencies:
  - base
  - z80
  - z80-utils
  - bytestring
  - filepath
  - directory
  - yaml
  - aeson
  - text
  - JuicyPixels
  - extra

default-extensions:
  - BinaryLiterals
  - NumericUnderscores
  - BlockArguments
  - RecursiveDo
  - NamedFieldPuns
  - RecordWildCards
  - LambdaCase

source-dirs:
  - src
  
executables:
  chip80-homelab2:
    main: main.hs
